export const goalsIcon = require("./goals.svg")
export const meter = require("./meter.svg")
export const diet = require("./diet.svg")
export const arrow = require("./arrow.svg")
export const defaultAvatar = require("./defaultAvatar.png")
export const SettingsIcon = require("./SeetingsIcon.svg")