const userList = [
    {
        id: "52373582",
        nameUser: "Tom Cruise",
        dateRegistor: "May 26, 2019 8:00 AM",
        sex: "Female",
        role: "admin",
        email: "adad@asd.ru",
    },
    {
        id: "55372358",
        nameUser: "Tomas Cruise",
        sex: "Male",
        dateRegistor: "May 25, 2019 8:00 AM",
        role: "user",
        email: "adad@asd.com",
    },
    {
        id: "5537235ada8",
        nameUser: "Tomas Cruise",
        sex: "Male",
        dateRegistor: "May 25, 2019 8:00 PM",
        role: "admin",
        email: "adad@asd.com",
    },
    {
        id: "55372358ada",
        nameUser: "Tomas Cruise",
        sex: "Male",
        dateRegistor: "May 25, 2019 8:00 AM",
        role: "user",
        email: "adad@asd.com",
    },
    {
        id: "5ada537358",
        nameUser: "Tomas Cruise",
        sex: "Male",
        dateRegistor: "May 25, 2015 11:00 AM",
        role: "user",
        email: "adad@asd.com",
    },
    {
        id: "553121272358",
        nameUser: "Tomas Cruise",
        sex: "Female",
        dateRegistor: "May 25, 2016 8:00 AM",
        role: "user",
        email: "adad@asd.com",
    },
    {
        id: "55122337358",
        nameUser: "Tomas Cruise",
        sex: "Male",
        dateRegistor: "May 10, 2015 8:00 AM",
        role: "user",
        email: "adad@asd.com",
    },
    {
        id: "122131323",
        nameUser: "Tomas Cruise",
        sex: "Male",
        dateRegistor: "May 25, 2019 8:00 AM",
        role: "user",
        email: "adad@asd.com",
    },
    {
        id: "5531232137358",
        nameUser: "Tomas Cruise",
        sex: "Male",
        dateRegistor: "May 25, 2019 8:00 AM",
        role: "user",
        email: "adad@asd.com",
    },
]

export { userList }
